{
  config,
  lib,
  ...
}:
let
  cfg = config.programs.hot-stylix;
  runtimePath = "${cfg.stateDir}/btop/hot-stylix-current.theme";
in
{
  options.programs.hot-stylix.targets.btop.enable = lib.mkEnableOption "runtime-managed btop theme" // {
    default = true;
  };

  config = lib.mkMerge [
    {
      hotStylix.supportedTargets.btop = {
        enable = config.programs.hot-stylix.targets.btop.enable;
        inherit runtimePath;

        shellFunctions = ''
          render_btop() {
            local scheme_file=$1
            local out_file=$2
            local base00="" base01="" base02="" base03="" base04="" base05="" base06="" base07=""
            local base08="" base09="" base0A="" base0B="" base0C="" base0D="" base0E="" base0F=""

            eval "$(emit_color_vars "$scheme_file")"

            cat > "$out_file" <<EOF
# Generated by hot-stylix
theme[main_bg]="$base00"
theme[main_fg]="$base05"
theme[title]="$base05"
theme[hi_fg]="$base0D"
theme[selected_bg]="$base03"
theme[selected_fg]="$base0D"
theme[inactive_fg]="$base04"
theme[graph_text]="$base06"
theme[meter_bg]="$base03"
theme[proc_misc]="$base06"
theme[cpu_box]="$base0E"
theme[mem_box]="$base0B"
theme[net_box]="$base0C"
theme[proc_box]="$base0D"
theme[div_line]="$base01"
theme[temp_start]="$base0B"
theme[temp_mid]="$base0A"
theme[temp_end]="$base08"
theme[cpu_start]="$base0B"
theme[cpu_mid]="$base0A"
theme[cpu_end]="$base08"
theme[free_start]="$base0A"
theme[free_mid]="$base0B"
theme[free_end]="$base0B"
theme[cached_start]="$base0C"
theme[cached_mid]="$base0C"
theme[cached_end]="$base0A"
theme[available_start]="$base08"
theme[available_mid]="$base0A"
theme[available_end]="$base0B"
theme[used_start]="$base0A"
theme[used_mid]="$base09"
theme[used_end]="$base08"
theme[download_start]="$base0B"
theme[download_mid]="$base0A"
theme[download_end]="$base08"
theme[upload_start]="$base0B"
theme[upload_mid]="$base0A"
theme[upload_end]="$base08"
theme[process_start]="$base0B"
theme[process_mid]="$base0A"
theme[process_end]="$base08"
EOF
          }
        '';

        render = ''
          render_btop "$scheme_file" "$tmp_path"
        '';

        reload = ''
          true
        '';
      };
    }
    (lib.mkIf config.programs.hot-stylix.targets.btop.enable {
      programs.btop.enable = lib.mkDefault true;
      programs.btop.package = lib.mkDefault null;
      programs.btop.settings.color_theme = lib.mkForce "hot-stylix-current";
      programs.btop.settings.theme_background = lib.mkIf (config.stylix.opacity.terminal != 1.0) false;

      xdg.configFile."btop/themes/hot-stylix-current.theme".source =
        config.lib.file.mkOutOfStoreSymlink runtimePath;
    })
  ];
}
